openapi: 3.0.3
info:
  title: Aftermath API
  version: 1.0.0
paths:
  /incidents:
    get:
      summary: List incidents
      responses:
        '200':
          description: A list of incidents
          content:
            application/json:
              schema:
                type: object
                properties:
                  incidents:
                    type: array
                    items:
                      $ref: '#/components/schemas/Incident'
  /incidents/{id}:
    get:
      summary: Get incident by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Incident details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Incident'
  /postmortems:
    post:
      summary: Create a postmortem
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Postmortem'
      responses:
        '201':
          description: Postmortem created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Postmortem'
    get:
      summary: List postmortems
      responses:
        '200':
          description: A list of postmortems
          content:
            application/json:
              schema:
                type: object
                properties:
                  postmortems:
                    type: array
                    items:
                      $ref: '#/components/schemas/Postmortem'
  /postmortems/{id}:
    get:
      summary: Get postmortem by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Postmortem details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Postmortem'
    put:
      summary: Update a postmortem
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Postmortem'
      responses:
        '200':
          description: Postmortem updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Postmortem'
  /actions:
    post:
      summary: Create an action
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Action'
      responses:
        '201':
          description: Action created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Action'
    get:
      summary: List actions
      responses:
        '200':
          description: A list of actions
          content:
            application/json:
              schema:
                type: object
                properties:
                  actions:
                    type: array
                    items:
                      $ref: '#/components/schemas/Action'
  /actions/{id}:
    patch:
      summary: Update action status
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
                  enum: [open, closed]
      responses:
        '200':
          description: Action updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Action'
  /metrics:
    get:
      summary: Get service metrics
      responses:
        '200':
          description: Metrics summary
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Metrics'
components:
  schemas:
    Incident:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        team:
          type: string
        status:
          type: string
          enum: [open, closed]
        severity:
          type: integer
        createdAt:
          type: string
          format: date-time
        resolvedAt:
          type: string
          format: date-time
        slaHours:
          type: integer
      required: [id, title, team, status, severity, createdAt, slaHours]
    Postmortem:
      type: object
      properties:
        id:
          type: integer
        incidentId:
          type: integer
        summary:
          type: string
        completedAt:
          type: string
          format: date-time
        tags:
          type: array
          items:
            type: string
      required: [id, incidentId, summary, completedAt, tags]
    Action:
      type: object
      properties:
        id:
          type: integer
        incidentId:
          type: integer
        description:
          type: string
        status:
          type: string
          enum: [open, closed]
        createdAt:
          type: string
          format: date-time
        closedAt:
          type: string
          format: date-time
      required: [id, incidentId, description, status, createdAt]
    Metrics:
      type: object
      properties:
        mttrPerIncident:
          type: array
          items:
            type: object
            properties:
              incidentId:
                type: integer
              mttrHours:
                type: number
            required: [incidentId, mttrHours]
        avgMttrHours:
          type: number
        slaCompliance:
          type: number
          description: Percentage of incidents resolved within SLA
        openActions:
          type: integer
      required: [mttrPerIncident, avgMttrHours, slaCompliance, openActions]
